Web/Controllers/MilkController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Services.Dtos;
using Services.IServices;

namespace MvcTemplate.Controllers
{
    /**[Authorize]
    public class MilkController : Controller
    {
        private IService Service { get; set; }
        public MilkController(IService service)
        {
            Service = service;
        }
        public async Task<IActionResult> Index()
        {

            MilkModels model = new MilkModels();
            model.Milks = await Service.GetAllMilks();
            return View(model);
        }


        public IActionResult AddMilk()
        {

            MilkModel model = new MilkModel();
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> AddMilk(MilkModel model)
        {
            if (ModelState.IsValid)
            {
                await Service.AddMilk(model.Liters, model.RecolectionDate);
                return RedirectToAction("Index");
            }
            return View(model);
        }
    }**/
}

Web/Views/Milk/AddMilk.cshtml
@using Services.Dtos;
@{
    ViewData["Title"] = "Add Milk";
}
@model MilkModel;
<div class="form-group">
    <form class="form-inline" asp-controller="Milk" asp-action="AddMilk">
        <input type="number" class="form-control" asp-for="Liters" placeholder="Liters" required />
        <input type="date" class="form-control" asp-for="RecolectionDate" required />   
        <button type="submit" class="btn btn-primary">Crear</button>
    </form>
</div>

Web/Views/Milk/Index.cshtml
@using Services.Dtos
@{
    ViewData["Title"] = "Home Page";
}
@model MilkModels;
<div class="text-center">
    @if (Model.Milks.Count > 0)
    {
        <ul>
            @for (int i = 0; i < Model.Milks.Count; i++)
            {
                <li> @(i + 1) @Model.Milks.ToArray()[i].Liters : @Model.Milks.ToArray()[i].RecolectionDate.ToString()</li>
            }
        </ul>
    }
    else
    {
        <h5>No hay produccion</h5>
    }

</div>